import type { DomainSeed } from "./layout";

export const MATH_ID = "math-root";

export const MATH_DOMAINS: DomainSeed[] = [
  {
    id: "math-numbers",
    title: "NÚMEROS",
    years: [6, 7, 8, 9],
    children: [
      { id: "num-naturais", title: "Naturais", years: [6] },
      { id: "num-inteiros", title: "Inteiros", years: [7] },
      { id: "num-fracoes", title: "Frações", years: [6, 7] },
      { id: "num-decimais", title: "Decimais", years: [6, 7] },
      { id: "num-porcentagem", title: "Porcentagem", years: [7, 8] },
      { id: "num-razao", title: "Razão", years: [8, 9] },
      { id: "num-proporcao", title: "Proporção", years: [8, 9] },
      { id: "num-potencias", title: "Potências", years: [8, 9] },
      { id: "num-raizes", title: "Raízes", years: [9] },
      { id: "num-notacao", title: "Notação científica", years: [9] },
    ],
  },
  {
    id: "math-algebra",
    title: "ÁLGEBRA",
    years: [7, 8, 9, 10],
    children: [
      { id: "alg-expressoes", title: "Expressões", years: [7] },
      { id: "alg-variaveis", title: "Variáveis", years: [7] },
      { id: "alg-equacoes", title: "Equações", years: [7, 8] },
      { id: "alg-inequacoes", title: "Inequações", years: [8] },
      { id: "alg-sistemas", title: "Sistemas", years: [8, 9] },
      { id: "alg-notaveis", title: "Produtos notáveis", years: [9] },
      { id: "alg-fatoracao", title: "Fatoração", years: [9] },
      { id: "alg-polinomios", title: "Polinômios", years: [10] },
      { id: "alg-segundograu", title: "Equação do 2º grau", years: [10] },
    ],
  },
  {
    id: "geo",
    title: "GEOMETRIA",
    years: [6, 7, 8, 9, 10, 11, 12],
    status: "prototype",
    children: [
      {
        id: "geo-angles",
        title: "Ângulos",
        years: [6, 7],
        conceptId: "geo-angles",
        code: "ANG",
        connects: ["geo-triangles", "geo-polygons"],
      },
      {
        id: "geo-polygons",
        title: "Polígonos",
        years: [7, 8],
        connects: ["geo-angles", "geo-perimeter", "geo-area"],
        children: [
          { id: "geo-poly-class", title: "Classificação", years: [7] },
          { id: "geo-poly-internos", title: "Ângulos internos", years: [8] },
          { id: "geo-poly-externos", title: "Ângulos externos", years: [8] },
          {
            id: "geo-poly-perimetro",
            title: "Perímetro",
            years: [7],
            connects: ["geo-perimeter"],
          },
          {
            id: "geo-poly-area",
            title: "Área",
            years: [7, 8],
            connects: ["geo-area"],
          },
        ],
      },
      {
        id: "geo-triangles",
        title: "Triângulos",
        years: [7, 8, 9],
        conceptId: "geo-triangles",
        code: "TRI",
        status: "prototype",
        connects: ["geo-pythagoras", "geo-angles", "geo-area"],
        children: [
          { id: "geo-tri-class", title: "Classificação", years: [7] },
          { id: "geo-tri-sum", title: "Soma dos ângulos", years: [7] },
          {
            id: "geo-tri-area",
            title: "Área",
            years: [7, 8],
            connects: ["geo-area"],
          },
          { id: "geo-tri-congruence", title: "Congruência", years: [9] },
          {
            id: "geo-tri-similarity",
            title: "Semelhança",
            years: [9],
            connects: ["geo-similarity"],
          },
          { id: "geo-tri-right", title: "Triângulo retângulo", years: [9] },
          {
            id: "geo-tri-pythagoras",
            title: "Pitágoras",
            years: [9],
            status: "prototype",
            connects: ["geo-pythagoras"],
          },
        ],
      },
      {
        id: "geo-perimeter",
        title: "Perímetro",
        years: [6, 7],
        conceptId: "geo-perimeter",
        code: "PER",
        connects: ["geo-area", "geo-polygons"],
      },
      {
        id: "geo-area",
        title: "Área",
        years: [7, 8],
        conceptId: "geo-area",
        code: "AREA",
        connects: ["geo-perimeter", "geo-pythagoras"],
      },
      {
        id: "geo-similarity",
        title: "Semelhança",
        years: [9],
        connects: ["geo-triangles", "geo-trigonometry"],
      },
      {
        id: "geo-congruence",
        title: "Congruência",
        years: [9],
        connects: ["geo-triangles"],
      },
      {
        id: "geo-pythagoras",
        title: "Pitágoras",
        years: [9, 10],
        conceptId: "geo-pythagoras",
        code: "PYT",
        connects: ["geo-triangles", "geo-area", "trig-triangle", "phy-vectors"],
      },
      {
        id: "geo-circle",
        title: "Circunferência",
        years: [8, 9],
        connects: ["geo-area"],
        children: [
          { id: "geo-cir-radio", title: "Raio", years: [7] },
          { id: "geo-cir-diametro", title: "Diâmetro", years: [7] },
          { id: "geo-cir-comprimento", title: "Comprimento", years: [8, 9] },
          { id: "geo-cir-area", title: "Área do círculo", years: [9] },
          { id: "geo-cir-arcos", title: "Arcos", years: [9] },
        ],
      },
      {
        id: "geo-space",
        title: "Geometria espacial",
        years: [10, 11],
        connects: ["geo-area", "geo-solid-volume"],
        children: [
          { id: "geo-space-prismas", title: "Prismas", years: [10] },
          { id: "geo-space-piramides", title: "Pirâmides", years: [10] },
          { id: "geo-space-cilindros", title: "Cilindros", years: [11] },
          { id: "geo-space-cones", title: "Cones", years: [11] },
          { id: "geo-space-esferas", title: "Esferas", years: [11] },
          {
            id: "geo-solid-area",
            title: "Área",
            years: [10],
            connects: ["geo-area"],
          },
          { id: "geo-solid-volume", title: "Volume", years: [10, 11] },
        ],
      },
      {
        id: "geo-analytic",
        title: "Geometria analítica",
        years: [11],
        connects: ["func-cartesiano", "geo-pythagoras"],
        children: [
          {
            id: "geo-ana-cartesiano",
            title: "Plano cartesiano",
            years: [9],
            connects: ["func-cartesiano"],
          },
          { id: "geo-ana-distancia", title: "Distância entre pontos", years: [11] },
          { id: "geo-ana-medio", title: "Ponto médio", years: [11] },
          { id: "geo-ana-retas", title: "Retas", years: [11] },
        ],
      },
    ],
  },
  {
    id: "math-measures",
    title: "MEDIDAS",
    years: [6, 7, 8, 9],
    children: [
      { id: "med-comprimento", title: "Comprimento", years: [6, 7] },
      {
        id: "med-perimetro",
        title: "Perímetro",
        years: [6],
        connects: ["geo-perimeter"],
      },
      {
        id: "med-area",
        title: "Área",
        years: [7],
        connects: ["geo-area"],
      },
      { id: "med-volume", title: "Volume", years: [8, 10], connects: ["geo-space"] },
      { id: "med-capacidade", title: "Capacidade", years: [6, 7] },
      { id: "med-escala", title: "Escala", years: [8, 9] },
      { id: "med-conversao", title: "Conversão de unidades", years: [6, 9] },
    ],
  },
  {
    id: "math-functions",
    title: "FUNÇÕES",
    years: [9, 10, 11, 12],
    children: [
      {
        id: "func-cartesiano",
        title: "Plano cartesiano",
        years: [9, 10],
        connects: ["geo-ana-cartesiano"],
      },
      {
        id: "func-afim",
        title: "Função afim",
        years: [10],
        connects: ["phy-mru"],
      },
      {
        id: "func-quadratica",
        title: "Função quadrática",
        years: [10, 11],
        connects: ["phy-mruv"],
      },
      { id: "func-exponencial", title: "Função exponencial", years: [11] },
      { id: "func-log", title: "Logaritmos", years: [11, 12] },
      { id: "func-sequencias", title: "Sequências", years: [10] },
      { id: "func-pa", title: "PA", years: [10] },
      { id: "func-pg", title: "PG", years: [11] },
    ],
  },
  {
    id: "math-stats",
    title: "ESTATÍSTICA",
    years: [6, 7, 8, 9, 11],
    children: [
      { id: "sta-tabelas", title: "Tabelas", years: [6, 7] },
      { id: "sta-graficos", title: "Gráficos", years: [6, 8] },
      { id: "sta-media", title: "Média", years: [7, 8] },
      { id: "sta-mediana", title: "Mediana", years: [8, 9] },
      { id: "sta-moda", title: "Moda", years: [7, 8] },
      { id: "sta-dispersao", title: "Dispersão", years: [11] },
      { id: "sta-probabilidade", title: "Probabilidade", years: [9, 10] },
      { id: "sta-combinatoria", title: "Combinatória", years: [11, 12] },
    ],
  },
  {
    id: "math-finance",
    title: "MAT. FINANCEIRA",
    shortTitle: "MATEMÁTICA FINANCEIRA",
    years: [8, 9, 10, 11, 12],
    children: [
      { id: "fin-porcentagem", title: "Porcentagem", years: [8, 9], connects: ["num-porcentagem"] },
      { id: "fin-desconto", title: "Aumento e desconto", years: [9] },
      { id: "fin-simples", title: "Juros simples", years: [10, 11] },
      { id: "fin-compostos", title: "Juros compostos", years: [11, 12] },
      { id: "fin-crescimento", title: "Crescimento", years: [11, 12] },
    ],
  },
  {
    id: "math-trig",
    title: "TRIGONOMETRIA",
    years: [9, 10, 11, 12],
    children: [
      {
        id: "trig-seno",
        title: "Seno",
        years: [11],
        connects: ["phy-vectors"],
      },
      { id: "trig-cosseno", title: "Cosseno", years: [11], connects: ["phy-vectors"] },
      { id: "trig-tangente", title: "Tangente", years: [11] },
      {
        id: "trig-triangle",
        title: "Triângulo retângulo",
        years: [9, 10],
        connects: ["geo-pythagoras", "geo-triangles"],
      },
      { id: "trig-circulo", title: "Círculo trigonométrico", years: [11] },
      { id: "trig-funcoes", title: "Funções trigonométricas", years: [12] },
    ],
  },
];
